server:
  port: 9034

spring:
  application:
    name: ONBOARDING-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/test-cdl-onboarding
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB

  mvc:
    async:
      request-timeout: 60s



employee:
  fetch:
    API: http://43.205.24.208:9020/employee/eCode/
  onboarding:
    add-API: http://43.205.24.208:9020/employee

user:
  onboarding:
    add-API: http://43.205.24.208:9021/user/add

#dms api

doc:
  upload:
    API: http://43.205.24.208:9023/documents/upload/
  fetch:
    api: http://43.205.24.208:9023/documents/access/
  onboarding-Directory: root-onboarding



eon:
  base:
    API: http://43.205.24.208:5000/

generate:
  session-id:
    API: http://43.205.24.208:5000/api/auth/login?RetFormat=JSON&user_id=admin&Password=admin123

job:
  post:
    base-API: http://43.205.24.208:5000/api/jobpost/getdata_int?RetFormat=JSON&getter=true&session_id=
    #base-API: http://43.205.24.208:5000/api/getdata_int/getlist?RetFormat=JSON&getter=false&session_id=
  application:
    #base-API: http://43.205.24.208:5000/api/jobappl/getdata?RetFormat=JSON&getter=false&session_id=
    base-API: http://43.205.24.208:5000/api/jobappl/getlist?RetFormat=JSON&getter=false&session_id=
    #base-API: http://43.205.24.208:5000/api/jobappl/getlist?RetFormat=JSON&getter=false&session_id=

tech:
  panel:
    base-API: http://43.205.24.208:5000/api/ipanel/getlist?RetFormat=JSON&getter=false&session_id=

interview:
  schedule:
    base-API: http://43.205.24.208:5000/api/intview/getlist?RetFormat=JSON&getter=false&session_id=
  feedback:
    base-API: http://43.205.24.208:5000/api/intfb/getlist?RetFormat=JSON&getter=false&session_id=

onboarding:
  personal:
    base-API: http://43.205.24.208:5000/api/onboard/getpers?RetFormat=JSON&getter=true&session_id=

  general:
    base-API: http://43.205.24.208:5000/api/onboard/getgen?RetFormat=JSON&getter=true&session_id=

  education:
    base-API: http://43.205.24.208:5000/api/onboard/getedu?RetFormat=JSON&getter=true&session_id=

  skill:
    base-API: http://43.205.24.208:5000/api/onboard/getskill?RetFormat=JSON&getter=true&session_id=

  family:
    base-API: http://43.205.24.208:5000/api/onboard/getfam?RetFormat=JSON&getter=true&session_id=

  bank:
    base-API: http://43.205.24.208:5000/api/onboard/getbank?RetFormat=JSON&getter=true&session_id=

  pf:
    base-API: http://43.205.24.208:5000/api/onboard/getpf?RetFormat=JSON&getter=true&session_id=

  language:
    base-API: http://43.205.24.208:5000/api/onboard/getlang?RetFormat=JSON&getter=true&session_id=

  interest:
    base-API: http://43.205.24.208:5000/api/onboard/getint?RetFormat=JSON&getter=true&session_id=

  prof-exp:
    base-API: http://43.205.24.208:5000/api/onboard/getexp?RetFormat=JSON&getter=true&session_id=

  prof-ref:
    base-API: http://43.205.24.208:5000/api/onboard/getref?RetFormat=JSON&getter=true&session_id=

  documents:
    base-API: http://43.205.24.208:5000/api/onboard/getdoc?RetFormat=JSON&getter=true&session_id=

  questionnaire:
    base-API: http://43.205.24.208:5000/api/onboard/getqnr?RetFormat=JSON&getter=true&session_id=

  candidate-declaration:
    base-API: http://43.205.24.208:5000/api/onboard/getcdecl?RetFormat=JSON&getter=true&session_id=

  hr-declaration:
    base-API: http://43.205.24.208:5000/api/onboard/gethdecl?RetFormat=JSON&getter=true&session_id=

  overall-status:
    base-API: http://43.205.24.208:5000/api/onboard/getdata_sts?RetFormat=JSON&getter=true&session_id=

  overall-status-list:
    base-API: http://43.205.24.208:5000/api/onbadmin/getlist?RetFormat=JSON&getter=false&session_id=

abort:
    employee:
      base-API: http://43.205.24.208:5000/api/onboard/mod_onbstatus?RetFormat=JSON&getter=true&session_id=

IT:
 proof:
  investment:
     status-API: http://localhost:9026/proof-of-investment/getItInvestmentProofSubmissionStatus/

 declaration:
      status-API: http://localhost:9026/it-declaration-info/getITDeclarartionStatusSubmission/














